/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/listings/ai-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate an AI-assisted listing draft
         * @description Generate a **draft** listing (trilingual title + description + a suggested
         *     category) from a seller-supplied photo and/or keywords. Implemented in
         *     VER-58.
         *
         *     This endpoint returns a draft only — it **never creates, prices, or
         *     publishes** a listing. The seller reviews/edits the draft and then submits
         *     a separate, authenticated `POST /listings`. Keywords and image contents
         *     are treated as untrusted data (prompt-injection safe).
         *
         *     Rate limited per caller. Requires the AI-assist key to be provisioned on
         *     the server; otherwise responds `503 ai_assist_unavailable`.
         *
         */
        post: operations["createListingAiDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP challenge for a phone number
         * @description **Stub** — finalized by the auth implementation issue (Board-escalation,
         *     ADR 0002). Sends a one-time code to the given phone number and returns a
         *     challenge handle. Rate limited per phone and per IP.
         *
         */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an OTP code and start a session
         * @description **Stub** — finalized by the auth implementation issue. Verifies the code
         *     for a challenge and, on success, returns a bearer session token and the
         *     authenticated user.
         *
         */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the localized category taxonomy
         * @description **Stub** — finalized by the taxonomy issue (ADR 0001). Returns the
         *     category tree with names resolved to the requested language via the
         *     `requested → en → any` fallback chain.
         *
         */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published listings
         * @description **Stub** — finalized by the listings issue. Paginated browse/filter.
         */
        get: operations["listListings"];
        put?: never;
        /**
         * Create a listing
         * @description **Stub** — finalized by the listings issue. Creates a listing authored in
         *     a single `content_language`. Requires authentication. A draft from
         *     `/listings/ai-draft` is never auto-created; the seller submits here.
         *
         */
        post: operations["createListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single listing
         * @description **Stub** — finalized by the listings issue.
         */
        get: operations["getListing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search listings
         * @description **Stub** — finalized by the search issue (Meilisearch). Full-text search
         *     over localized listing fields with optional category filter.
         *
         */
        get: operations["searchListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Canonical error envelope (ADR 0003). EVERY non-2xx response uses this
         *     shape. `code` is a stable, machine-readable slug (e.g. `rate_limited`,
         *     `ai_assist_unavailable`); `message` is human-readable and may change.
         *      */
        Error: {
            error: {
                /** @description Stable machine-readable error code. */
                code: string;
                /** @description Human-readable description (not for branching on). */
                message: string;
            };
        };
        /**
         * @description Supported content/UI language (ADR 0001).
         * @enum {string}
         */
        Lang: "en" | "si" | "ta";
        /** @description A text value in English, Sinhala, and Tamil (ADR 0001). */
        Trilingual: {
            en: string;
            si: string;
            ta: string;
        };
        /**
         * @description Closed category taxonomy slug. Single source of truth is the backend
         *     `Categories` set (server-re-validated on AI drafts). Extended via the
         *     taxonomy issue, not ad hoc.
         *
         * @enum {string}
         */
        CategorySlug: "electronics" | "vehicles" | "property" | "home_garden" | "fashion" | "mobile_phones" | "services" | "jobs" | "pets" | "other";
        /** @description AI-generated draft listing returned by `POST /listings/ai-draft`. Note
         *     what is deliberately ABSENT: price, publish, featured, urgent — the model
         *     has no field to escalate into. The draft is editor input only.
         *      */
        ListingDraft: {
            category_suggestion: components["schemas"]["CategorySlug"];
            title: components["schemas"]["Trilingual"];
            description: components["schemas"]["Trilingual"];
            /** @description True when the model could not confidently draft (unreadable/off-topic
             *     photo, or a category that failed server-side re-validation).
             *      */
            needs_human_review: boolean;
            /** @description Brief reviewer-facing note; present when needs_human_review is true. */
            review_note?: string;
        };
        OtpRequest: {
            /**
             * @description Phone number; normalized to E.164 server-side (ADR 0002).
             * @example +94771234567
             */
            phone: string;
            /**
             * @default login
             * @enum {string}
             */
            purpose: "signup" | "login";
        };
        OtpChallenge: {
            /** Format: uuid */
            challenge_id: string;
            /** Format: date-time */
            expires_at: string;
        };
        OtpVerify: {
            /** Format: uuid */
            challenge_id: string;
            /** @description The OTP code the user received. */
            code: string;
        };
        Session: {
            /** @description Bearer session token (see bearerAuth). */
            token: string;
            /** Format: date-time */
            expires_at?: string;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** @description E.164 phone number (nullable for future email-only users). */
            phone?: string | null;
            display_name: string;
            preferred_language: components["schemas"]["Lang"];
        };
        /** @description A taxonomy category with its name resolved to the requested language. */
        Category: {
            slug: components["schemas"]["CategorySlug"];
            /** @description Localized display name (fallback-resolved). */
            name: string;
            parent_slug?: string | null;
            sort_order?: number;
        };
        ListingCreate: {
            category: components["schemas"]["CategorySlug"];
            content_language: components["schemas"]["Lang"];
            /** @description Authored in the single content_language. */
            title: string;
            description: string;
            /** @description Optional asking price in LKR. Set by the seller, never by AI. */
            price_lkr?: number | null;
        };
        /** @description A published listing. Title/description are returned resolved to the
         *     requested language (with machine-translation fallback per ADR 0001).
         *      */
        Listing: {
            /** Format: uuid */
            id: string;
            category: components["schemas"]["CategorySlug"];
            content_language: components["schemas"]["Lang"];
            title: string;
            description: string;
            price_lkr?: number | null;
            /**
             * @description Source of the returned localized text (ADR 0001).
             * @enum {string|null}
             */
            translation_source?: "human" | "machine" | null;
            /** Format: date-time */
            created_at: string;
        };
        ListingSummary: {
            /** Format: uuid */
            id: string;
            category: components["schemas"]["CategorySlug"];
            title: string;
            price_lkr?: number | null;
            /**
             * Format: uri
             * @description URL of the listing's primary thumbnail image, or null if none.
             */
            thumbnail_url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description A page of listing summaries. */
        ListingPage: {
            items: components["schemas"]["ListingSummary"][];
            page: number;
            pageSize: number;
            /** @description Total matching listings across all pages. */
            total: number;
            /** @description Category facet counts returned by search endpoints (absent on listing-only endpoints). */
            facets?: {
                [key: string]: number;
            };
        };
    };
    responses: {
        /** @description The request was malformed or failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication is required or failed. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests; slow down. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Preferred response language; falls back `requested → en → any` (ADR 0001). */
        LangQuery: components["schemas"]["Lang"];
        PageQuery: number;
        PageSizeQuery: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createListingAiDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description Optional free-text keywords describing the item (≤ 2 KB).
                     *     Treated as untrusted data, never instructions.
                     *      */
                    keywords?: string;
                    /**
                     * Format: binary
                     * @description Optional product photo (≤ 5 MiB; jpeg, png, webp, or gif).
                     *     Resize to ~1000px long edge client-side before upload.
                     *
                     */
                    image?: string;
                };
            };
        };
        responses: {
            /** @description A generated draft listing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDraft"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Keywords or image exceed the size limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unsupported image media type. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description Upstream AI provider failed to produce a draft. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description AI-assist is not configured / spend cap reached on this server. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description OTP dispatched (or accepted for dispatch). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpChallenge"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerify"];
            };
        };
        responses: {
            /** @description Verified; session established. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                /** @description Preferred response language; falls back `requested → en → any` (ADR 0001). */
                lang?: components["parameters"]["LangQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    listListings: {
        parameters: {
            query?: {
                /** @description Preferred response language; falls back `requested → en → any` (ADR 0001). */
                lang?: components["parameters"]["LangQuery"];
                category?: components["schemas"]["CategorySlug"];
                page?: components["parameters"]["PageQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of listing summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
        };
    };
    createListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingCreate"];
            };
        };
        responses: {
            /** @description Listing created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getListing: {
        parameters: {
            query?: {
                /** @description Preferred response language; falls back `requested → en → any` (ADR 0001). */
                lang?: components["parameters"]["LangQuery"];
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    searchListings: {
        parameters: {
            query: {
                /** @description The search query. */
                q: string;
                /** @description Preferred response language; falls back `requested → en → any` (ADR 0001). */
                lang?: components["parameters"]["LangQuery"];
                category?: components["schemas"]["CategorySlug"];
                page?: components["parameters"]["PageQuery"];
                pageSize?: components["parameters"]["PageSizeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingPage"];
                };
            };
        };
    };
}
